### ISSUE TITLE
Images not included in the repo, preventing development loading

### ISSUE THREAD

**Issue by christoomey** [kevinjalbert/github-tell-me-when-it-closes-extension#1]
Hey there! First and foremost, thank you so much for building these extensions. This was always the intended direction for Tell Me When It Closes, we've just not yet had time to build out the extensions. But thanks to you, the world now has them!

One small issue I've run into is the `images/` directory seems to be missing from the repo. This causes Chrome to complain and prevent loading as an unpacked extension. I've been able to work around by removing the image section from the manifest, but ideally the images would be included to prevent this issue.

**Comment by kevinjalbert** [comment]
Hello @christoomey! Ah, my bad, I was pruning things as I was committing (didn't want to commit unnecessary images) and I guess I went a little overboard.

I'll address this tonight.

**Comment by kevinjalbert** [comment]
@christoomey just merged in #3, which should solve the issue. Let me know if you are still hitting this issue.
